### ISSUE TITLE
Cannot install extension in VSCode 1.9.1

### ISSUE THREAD

**Issue by kbenjamin** [pavel-purma/vscode-copy-watcher#1]
Installing extension returns the following error:
`Couldn't find a compatible version of Copy Watcher with this version of Code.`

Looks like a interesting extension and solves a problem I have. Looking forward to seeing it in action.

**Comment by pavel-purma** [comment]
Hi, I have vscode 1.10.2. Extension has been written yesterday for use in our company. Not tested or created on previous version of vscode. Today I released version 1.0.2 with some fixes. Do you have that last version? What OS do you have? Windows?

**Comment by kbenjamin** [comment]
I updated VSCode to 1.10.2 and all is well. Giving it a try now. 

A couple of documentation comments: 

- "destinationRequired: true, is missing a quote in your example
- destination: Destination folder (relative to workspace root folder) - I was able to use any path (which is better) i.e. ${workspaceRoot}_common/...

Thanks for the plugin :)
